services:
  - type: web
    name: vacursio
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
